!function(i){function e(e){for(var t,n,r=e[0],o=e[1],a=0,s=[];a<r.length;a++)n=r[a],l[n]&&s.push(l[n][0]),l[n]=0;for(t in o)Object.prototype.hasOwnProperty.call(o,t)&&(i[t]=o[t]);for(u&&u(e);s.length;)s.shift()()}var n={},d={portal:0},l={portal:0};function p(e){if(n[e])return n[e].exports;var t=n[e]={i:e,l:!1,exports:{}};return i[e].call(t.exports,t,t.exports,p),t.l=!0,t.exports}p.e=function(c){var e=[];d[c]?e.push(d[c]):0!==d[c]&&{1:1}[c]&&e.push(d[c]=new Promise(function(e,r){for(var t={0:"31d6cfe0d16ae931b73c",1:"8d32e5e81b17cb241647"}[c]+".css",o=p.p+t,n=document.getElementsByTagName("link"),a=0;a<n.length;a++){var s=(l=n[a]).getAttribute("data-href")||l.getAttribute("href");if("stylesheet"===l.rel&&(s===t||s===o))return e()}var i=document.getElementsByTagName("style");for(a=0;a<i.length;a++){var l;if((s=(l=i[a]).getAttribute("data-href"))===t||s===o)return e()}var u=document.createElement("link");u.rel="stylesheet",u.type="text/css",u.onload=e,u.onerror=function(e){var t=e&&e.target&&e.target.src||o,n=new Error("Loading CSS chunk "+c+" failed.\n("+t+")");n.request=t,delete d[c],u.parentNode.removeChild(u),r(n)},u.href=o,document.getElementsByTagName("head")[0].appendChild(u)}).then(function(){d[c]=0}));var t,n=l[c];if(0!==n)if(n)e.push(n[2]);else{var r=new Promise(function(e,t){n=l[c]=[e,t]});e.push(n[2]=r);var o,a=document.createElement("script");a.charset="utf-8",a.timeout=120,p.nc&&a.setAttribute("nonce",p.nc),a.src=p.p+""+({}[t=c]||t)+"-"+{0:"423e8b5f697e5ef7f29f",1:"2150650efe1b7dc4ea9c"}[t]+".js",o=function(e){a.onerror=a.onload=null,clearTimeout(s);var t=l[c];if(0!==t){if(t){var n=e&&("load"===e.type?"missing":e.type),r=e&&e.target&&e.target.src,o=new Error("Loading chunk "+c+" failed.\n("+n+": "+r+")");o.type=n,o.request=r,t[1](o)}l[c]=void 0}};var s=setTimeout(function(){o({type:"timeout",target:a})},12e4);a.onerror=a.onload=o,document.head.appendChild(a)}return Promise.all(e)},p.m=i,p.c=n,p.d=function(e,t,n){p.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:n})},p.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},p.t=function(t,e){if(1&e&&(t=p(t)),8&e)return t;if(4&e&&"object"==typeof t&&t&&t.__esModule)return t;var n=Object.create(null);if(p.r(n),Object.defineProperty(n,"default",{enumerable:!0,value:t}),2&e&&"string"!=typeof t)for(var r in t)p.d(n,r,function(e){return t[e]}.bind(null,r));return n},p.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return p.d(t,"a",t),t},p.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},p.p="/bundle/",p.oe=function(e){throw console.error(e),e};var t=window.webpackJsonp=window.webpackJsonp||[],r=t.push.bind(t);t.push=e,t=t.slice();for(var o=0;o<t.length;o++)e(t[o]);var u=r;p(p.s=0)}({"./source-bundle/js/global.js":
/*!************************************!*\
  !*** ./source-bundle/js/global.js ***!
  \************************************/
/*! no exports provided */function(e,t,n){"use strict";n.r(t);var r=n(/*! swiper-init */"./source-bundle/js/modules/swiper-init.js"),o=n(/*! collapse */"./source-bundle/js/modules/collapse.js"),a=n(/*! nav-menu-flyout */"./source-bundle/js/modules/nav-menu-flyout.js");window._paq="object"==typeof window._paq?window._paq:[],window._gaq="object"==typeof window._gaq?window._gaq:[],document.addEventListener("DOMContentLoaded",function(e){Object(o.default)(),r.init(r.apply),Object(a.default)()})},"./source-bundle/js/modules/blaetter.js":
/*!**********************************************!*\
  !*** ./source-bundle/js/modules/blaetter.js ***!
  \**********************************************/
/*! exports provided: portal_url, jsbase, set_webpack_publicpath, is_palm, languageCode, load, isElementVisible */function(e,t,n){"use strict";function r(){return document.getElementById("echo-behavior-js").src.replace(/\/css\/.*/,"")}function o(){return document.getElementById("echo-behavior-js").src.replace(/js\/[^\/]+$/,"")}function a(){window.__webpack_public_path__=o()+"/"}function s(){var e=document.querySelector("#header .portal-claim");return!e||"none"===window.getComputedStyle(e,null).display}function i(){return(document.documentElement.lang||"de").substring(0,2)}function l(s){if(Array.isArray(s)){var t=this,n=[];return s.forEach(function(e){n.push(t.bo_script(e))}),Promise.all(n)}return new Promise(function(t,e){var n=!1;function r(e){n||this.readyState&&"complete"!==this.readyState||(this.readyState="complete",n=!0,t(this))}var o=document.getElementsByTagName("script")[0],a=document.querySelector('script[src="'+s+'"]');a?"complete"===a.readyState?t(this):(a.addEventListener("load",r.bind(a)),a.addEventListener("readystatechange",r.bind(a)),a.addEventListener("error",e),a.addEventListener("abort",e)):((a=document.createElement("script")).type="text/javascript",a.src=s,a.onload=a.onreadystatechange=r,a.onerror=a.onabort=e,o.parentNode.insertBefore(a,o))})}function u(e){var t=e.getBoundingClientRect(),n=window.innerWidth||doc.documentElement.clientWidth,r=window.innerHeight||doc.documentElement.clientHeight,o=function(e,t){return document.elementFromPoint(e,t)};return!(t.right<0||t.bottom<0||t.left>n||t.top>r)&&(e.contains(o(t.left,t.top))||e.contains(o(t.right,t.top))||e.contains(o(t.right,t.bottom))||e.contains(o(t.left,t.bottom)))}n.r(t),n.d(t,"portal_url",function(){return r}),n.d(t,"jsbase",function(){return o}),n.d(t,"set_webpack_publicpath",function(){return a}),n.d(t,"is_palm",function(){return s}),n.d(t,"languageCode",function(){return i}),n.d(t,"load",function(){return l}),n.d(t,"isElementVisible",function(){return u})},"./source-bundle/js/modules/collapse.js":
/*!**********************************************!*\
  !*** ./source-bundle/js/modules/collapse.js ***!
  \**********************************************/
/*! exports provided: default */function(e,t,n){"use strict";n.r(t),function(a){t.default=function(){a(".js-collapse-me").each(function(){var e=a(this),t=a(this).data("opentext")||"Öffnen",n=a(this).data("closetext")||"Schließen";e.wrapInner('<span class="js-collapse-me-inner"></span> '),e.prepend('<span class="js-collapse-me-toggler" title="">'+t+"</span>"),e.show(),a(".js-collapse-me-toggler",this).click(function(){e.toggleClass("opened"),e.hasClass("opened")?a(".js-collapse-me-toggler",e).html(n):a(".js-collapse-me-toggler",e).html(t)})}),a(".js-simple-toggler").each(function(){var e=a(this),t=a(this).data("target"),n=a(this).data("opentext"),r=a(this).data("closetext"),o=a(this).data("allowtoggle");a(t).hasClass("display-block")?r&&e.html(r):(a(t).addClass("display-none"),n&&e.html(n)),e.click(function(){a(t).hasClass("display-block")?(a(t).removeClass("display-block"),a(t).addClass("display-none"),e.html(n)):(a(t).removeClass("display-none"),a(t).addClass("display-block"),e.html(r)),0==o&&e.remove()})})}}.call(this,n(/*! jquery */"jquery"))},"./source-bundle/js/modules/nav-menu-flyout.js":
/*!*****************************************************!*\
  !*** ./source-bundle/js/modules/nav-menu-flyout.js ***!
  \*****************************************************/
/*! exports provided: default */function(e,t,r){"use strict";r.r(t),function(n){r.d(t,"default",function(){return e});r(/*! blaetter */"./source-bundle/js/modules/blaetter.js");function e(){var e=n(".js-hamburger"),t=n("#navigation-primary");e.click(function(e){return e.preventDefault(),n(this).hasClass("opened")?(n(this).removeClass("opened").attr("aria-label","Navigation aufklappen"),t.removeClass("opened")):(n(this).addClass("opened").attr("aria-label","Navigation zuklappen"),t.addClass("opened")),!1}),n("#navigation-primary ul.menu > li.menu-item--collapsed > a, #navigation-primary ul.menu > li.menu-item--expanded > a").each(function(){n(this).after('<button class="arrow"><i class="fa fa-chevron-down" aria-hidden="true"></i></button>')}),n("#navigation-primary ul.menu > li.menu-item--collapsed .arrow, #navigation-primary ul.menu > li.menu-item--expanded .arrow").click(function(e){e.preventDefault(),n("#navigation-primary ul.menu > li.menu-item--expanded .arrow").not(this).parent().removeClass("menu-item--expanded").addClass("menu-item--collapsed"),n(this).parent().hasClass("menu-item--collapsed")?n(this).parent().removeClass("menu-item--collapsed").addClass("menu-item--expanded"):n(this).parent().removeClass("menu-item--expanded").addClass("menu-item--collapsed")})}}.call(this,r(/*! jquery */"jquery"))},"./source-bundle/js/modules/swiper-init.js":
/*!*************************************************!*\
  !*** ./source-bundle/js/modules/swiper-init.js ***!
  \*************************************************/
/*! exports provided: init, slidesperview, apply */function(e,a,s){"use strict";s.r(a),function(r){s.d(a,"init",function(){return t}),s.d(a,"slidesperview",function(){return n}),s.d(a,"apply",function(){return o});var e=s(/*! blaetter */"./source-bundle/js/modules/blaetter.js");function t(t){if(!r(".swiper,.swiper-wrapper").length)return!1;e.set_webpack_publicpath(),s.e(/*! import() */1).then(s.t.bind(null,/*! swiper/dist/css/swiper.css */"./node_modules/swiper/dist/css/swiper.css",7)),s.e(/*! import() */0).then(s.t.bind(null,/*! swiper */"./node_modules/swiper/dist/js/swiper.esm.bundle.js",7)).then(function(e){t(e.default)}).catch(function(e){console.log(e)})}function n(e,t){var n=e&&r(e).data("slidesperview");return e&&r.extend(t,{slidesPerView:n,slidesPerGroup:n,lazy:{loadPrevNextAmount:n}}),t}function o(e){new e(".archive-index.swiper",{grabCursor:!0,slideToClickedSlide:!0,direction:"horizontal",slidesPerView:12,slidesPerGroup:12,spaceBetween:24,loop:!1,preloadImages:!1,touchReleaseOnEdges:!0,autoHeight:!0,touchEventsTarget:"swiper-wrapper",watchOverflow:!0,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},breakpoints:{1e3:{slidesPerView:6,slidesPerGroup:6},420:{slidesPerView:4,slidesPerGroup:4}}})}}.call(this,s(/*! jquery */"jquery"))},"./source-bundle/style.scss":
/*!**********************************!*\
  !*** ./source-bundle/style.scss ***!
  \**********************************/
/*! no static exports found */function(e,t,n){},0:
/*!*********************************************************************!*\
  !*** multi ./source-bundle/js/global.js ./source-bundle/style.scss ***!
  \*********************************************************************/
/*! no static exports found */function(e,t,n){n(/*! /app/source-bundle/js/global.js */"./source-bundle/js/global.js"),e.exports=n(/*! /app/source-bundle/style.scss */"./source-bundle/style.scss")},jquery:
/*!*************************!*\
  !*** external "jQuery" ***!
  \*************************/
/*! no static exports found */function(e,t){e.exports=jQuery}});
//# sourceMappingURL=portal.js-30241c900b4bb33cea46.map